version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:9.4.12-alpine
        # 環境情報を追加
        environment:
          - POSTGRES_USER=root
          - POSTGRES_DB=blog_test
    # ディレクトリ情報を移動（こうしないとエラーになる）
    working_directory: ~/blog
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      # DBのセットアップを修正
      - run:
          name: Database setup
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate

      # run tests!
      # RSpecの実行も修正
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            "${TEST_FILES}"

      # Save test results for timing analysis
      - store_test_results:
          path: test_results