default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("DB_PASSWORD") {''} %>
  socket: <%= ["/run/mysqld/mysqld5.6.sock",
               "/tmp/mysqld.sock",
               "/var/run/mysqld/mysqld.sock",
               "/var/lib/mysql/mysql.sock"].detect {|s| File.exist?(s) } %>

development:
  <<: *default
  database: blog_development


test:
  <<: *default
  database: blog_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: blog_production
  username: <%= Rails.application.credentials.conoha[:blog_username] %>
  password: <%= Rails.application.credentials.conoha[:blog_password] %>
  socket: /var/lib/mysql/mysql.sock
  host: <%= ENV['DB_HOST'] %>