default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: blog_development


test:
  <<: *default
  database: blog_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: blog_production
  username: <%= ENV['BLOG_USERNAME'] %>
  password: <%= ENV['BLOG_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
  host: <%= ENV['DB_HOST'] %>